git: Add locking mechanism to post-checkout tag generation script

diff --git a/git/.git-templates/hooks/post-checkout b/git/.git-templates/hooks/post-checkout
--- a/git/.git-templates/hooks/post-checkout
+++ b/git/.git-templates/hooks/post-checkout
@@ -1,6 +1,26 @@
 #!/usr/bin/env sh
 
-# TODO: Remove .tags first?
-# Sometimes ctags refuses to overwrite `.tags` because it doesn't recoqnize it as a tags file
-# Maybe something goes wrong, the file is corrupted, and then it's stuck like that?
-git ls-files | ctags -L - -f .tags >/dev/null 2>&1 &
+MAX_TRIES=10
+
+generate_tags() {
+  git ls-files | ctags -L - -f .tags >/dev/null 2>&1 &
+  rm .tags.lock
+}
+
+acquire_lock() {
+  i=0
+  while [ $i -lt $MAX_TRIES -a -f .tags.lock ]; do
+    sleep 1
+    let i=i+1
+  done
+
+  if [ $i -eq $MAX_TRIES ]; then
+    echo "Couldn't acquire .tags.lock"
+    exit 1
+  fi
+
+  touch .tags.lock
+}
+
+acquire_lock
+generate_tags
